import Head from 'next/head'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'
// Here import "../styles.css" will not work. have to import the css in form of module files.

{/* 
  Stores the styles in an object , where the key is the name of the class and the value is unique identifier that is given by nextJs.
*/}

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <style jsx>
        {`
          .mySpan {
            color : dimgray ;
          } 
          
          h2 {
            font-size : 38px ;
          }

          h3 {
            font-size : 28px ;
          }
        `}
      </style>

      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><li>Home</li></Link>
          <Link href='/about' replace={true}><li>About</li></Link> {/* replace - Replace the current history state instead of adding a new url into the stack. Defaults to false*/ }
          <Link href='/blog'><li>Blogs</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
        </ul>
      </nav>
      
      <main className={styles.main}>

        <h1 className={styles.title}><span className='mySpan'>Hunting coder</span></h1>

        <div className={styles.imageWrapper}>
          <Image className={styles.myImg} src="/homeimg.avif" width={237} height={158}></Image>
        </div>
        <p className={styles.description}>
          A Blog for Hunting coder by hunter coder.
        </p>

        <div className='blogs'>
          <h2>Popular blogs</h2>
          <div className='blogItem'>
            <h3>Lorem Ipsum</h3>
            <p>The things in the blogs are beautiful. Learning NextJs is beautiful.</p>
          </div>
        </div>

      </main>
    </>
  )
}
