import Head from 'next/head'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blogs</li>
          <li>Contact</li>
        </ul>
      </nav>
      
      <main className={styles.main}>

        <h1 className={styles.title}>Hunting coder</h1>
      
        <p className={styles.description}>
          A Blog channel for Hunting coder my hunter coder.
        </p>

        <div className='blogs'>
          <h2>Popular blogs</h2>
          <div className='blogItem'>
            <h3>Lorem Ipsum</h3>
            <p>The things in the blogs are beautiful. Learning NextJs is beautiful.</p>
          </div>
        </div>

      </main>
    </>
  )
}
